name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cmd: [ "nix flake check -L --show-trace", "nix build .#hello" ]
    runs-on: ${{ matrix.os }}
    name: nix-build
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: ${{ matrix.cmd }}
